OBJS = ReverseWords.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

ReverseWords : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o ReverseWords

ReverseWords.o : ReverseWords.cpp
			 $(CC) $(CFLAGS) ReverseWords.cpp
			 
clean:
	\rm *.o *~ ReverseWords